[package]
name = "updater"
version = "0.1.0"
authors = ["James Prestwich <james@nomad.xyz>"]
edition = "2021"

[dependencies]
tokio = { version = "1.0.1", features = ["rt", "macros"] }
config = "0.11.0"
serde = "1.0.120"
serde_json = { version = "1.0.61", default-features = false }
log = "0.4.13"
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
thiserror = { version = "1.0.22", default-features = false }
async-trait = { version = "0.1.42", default-features = false }
futures-util = "0.3.12"
color-eyre = "0.5.0"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb" }
nomad-xyz-configuration = { path = "../../configuration" }

nomad-core = { path = "../../nomad-core" }
nomad-base = { path = "../../nomad-base" }
nomad-ethereum = { path = "../../chains/nomad-ethereum" }
affix = "0.1.2"

prometheus = "0.12"
warp = "0.3"
hex = "0.4.3"

[dev-dependencies]
mockall = "0.9.1"
nomad-test = { path = "../../nomad-test" }
dotenv = "0.15.0"
serial_test = "0.6.0"